[project]
name = "champs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "plotly>=6.3.0",
    "pydantic>=2.11.7",
    "rich>=14.1.0",
    "selectolax>=0.3.33",
    "streamlit>=1.48.1",
]
